# Generated by Django 3.2 on 2025-02-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('films', 'Films'), ('people', 'People'), ('locations', 'Locations'), ('species', 'Species'), ('vehicles', 'Vehicles')], max_length=20),
        ),
    ]
